# DON'T EDIT THIS!
#
# Codecrafters relies on this file being intact to run tests successfully. Any changes
# here will not reflect when CodeCrafters tests your code, and might even cause build
# failures.
#
# DON'T EDIT THIS!
name: hs-http-server-clone
version: 0.1.0.0
license: BSD3

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - network # establish a simple TCP network
  - bytestring # useful to send bytes over the network
  - hslogger >= 1.3.1 && < 1.3.2 # to log messages
  - safe >= 0.3.19 && < 0.4 # to handle exceptions
  - split >= 0.2.3 && < 0.3 # to split strings
  - optparse-applicative >= 0.17 && < 0.18 # to parse command line arguments
  - mtl >= 2.2.2 && < 2.3 # to handle monads

executables:
  hs-http-server-clone-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
